### ISSUE TITLE
Cannot create user session

### ISSUE THREAD

**Issue by fschwarz86** [hellqvio86/casambi#5]
Hi there,

I'm coming here based on your post in the HASS community - thanks for that!

It seems I still cannot initiate a user session. I've tried the following snippet, but end up in a 410 error (which kinda makes sense, as the session header is not populated):

```
import casambi
import time

api_key = 'MY_API_KEY'
email = 'MY_EMAIL'
network_password = 'MY_NETWORK_PASSWORD'
user_password = 'MY_USER_PASSWORD'

worker = casambi.Casambi(api_key=api_key, email=email, \
user_password=user_password, network_password=network_password)
# worker.create_user_session()
worker.create_network_session()
worker.ws_open()

units = worker.get_unit_list()
print("units: {}".format(units))

worker.ws_close()
```

Result:
```
Traceback (most recent call last):
  File "/home/fschwarz/Downloads/casambi/test.py", line 16, in <module>
    units = worker.get_unit_list()
  File "/home/fschwarz/.local/lib/python3.10/site-packages/casambi/__init__.py", line 754, in get_unit_list
    raise CasambiApiException(reason)
casambi.CasambiApiException: get_network_unit_list: headers: {'X-Casambi-Key': 'MY_API_KEY', 'X-Casambi-Session': None, 'Content-type': 'application/json'},message: "Got a invalid status_code",status_code: 410,response: <html><head><title>Error 410</title></head><body style='margin:20px; font-family:sans-serif; font-size: 20px;'>ERROR 410: Gone</body></html>
```

If I uncomment `worker.create_user_session()`, I'm ending up in a 401.

The API documentation says

> Note that network session works only with network credentials. If you have site user credentials then you should use user session instead.

which makes me thinking that I have to use *either* create_network_session() *or* create_user_session(). The Casambi developer page also allows me to receive a session token from the network session just fine (and continue with that).

Any idea what I'm doing wrong here?

Thanks a ton,
Florian

**Comment by hellqvio86** [comment]
I found a typo in a print, but that will not fix your problem (released a new version of the library with a fix for that).

The example  works for me (but I have valid user site credentials and network credentials). 

The casambi library does not handle the network session correct, aiocasambi library will do that, please try that: https://github.com/hellqvio86/aiocasambi

But I think you are missing this step: http://support.casambi.com/support/solutions/articles/12000041325-how-to-create-a-site

Most miss that

**Comment by hellqvio86** [comment]
Latest version (**0.163**) will now support login through either **create_user_session** or **create_network_session**.

It does not support multiple networks, I take the first network id and use it.

Try that version and see what you get

**Comment by fschwarz86** [comment]
Thanks!! This seems to work just fine:

```
units: {'1': {'id': 1, 'address': '4202226b11c2', 'name': 'Mito volo', 'firmwareVersion': '26.10', 'position': 0, 'fixtureId': 6660, 'groupId': 0, 'type': 'Luminaire'}}
```

It would be great if you could propagate the same change to your aiocasambi project for use in the Home Assistant integration. :)

**Comment by hellqvio86** [comment]
It's already implemented in aiocasambi, so it's probably something else or a bug. Please  try aiocasambi/home_assistant_casambi in debug mode and see what happens, so we have something to debug with 🙂
